version: 2
before:
  hooks:
    - go mod download
archives:
  - id: darwin
    ids: ['darwin']
    formats: [ 'zip' ]
  - id: linux
    ids: [ 'linux']
    formats: [ 'zip' ]
  - id: windows
    ids: ['windows']
    formats: [ 'zip' ]
homebrew_casks:
  - ids:
      - darwin
    url:
      verified: github.com/attachmentgenie/{{.ProjectName}}"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/{{.ProjectName}}"]
          end
    repository:
      owner: attachmentgenie
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
builds:
  - id: darwin
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64
  - id: linux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: windows
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
dockers:
  - image_templates:
      - "ghcr.io/attachmentgenie/{{.ProjectName}}:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.source https://github.com/attachmentgenie/{{.ProjectName}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/attachmentgenie/{{.ProjectName}}:{{ .Version }}-arm64v8"
    use: buildx
    goarch: arm64
    goarm: "8"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--label=org.opencontainers.image.source https://github.com/attachmentgenie/{{.ProjectName}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64/v8"
docker_manifests:
  - name_template: "ghcr.io/attachmentgenie/{{.ProjectName}}:{{ .Version }}"
    image_templates:
      - "ghcr.io/attachmentgenie/{{.ProjectName}}:{{ .Version }}-amd64"
      - "ghcr.io/attachmentgenie/{{.ProjectName}}:{{ .Version }}-arm64v8"
  - name_template: "ghcr.io/attachmentgenie/{{.ProjectName}}:v{{ .Major }}"
    image_templates:
      - "ghcr.io/attachmentgenie/{{.ProjectName}}:{{ .Version }}-amd64"
      - "ghcr.io/attachmentgenie/{{.ProjectName}}:{{ .Version }}-arm64v8"
  - name_template: "ghcr.io/attachmentgenie/{{.ProjectName}}:latest"
    image_templates:
      - "ghcr.io/attachmentgenie/{{.ProjectName}}:{{ .Version }}-amd64"
      - "ghcr.io/attachmentgenie/{{.ProjectName}}:{{ .Version }}-arm64v8"
nfpms:
  - id: linux
    maintainer: 'bram vogelaar <bram@attachmentgenie.com>'
    package_name: "{{.ProjectName}}"
    ids: [ 'linux']
    formats:
      - deb
      - rpm
sboms:
  - artifacts: archive
release:
  prerelease: auto
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
