version: 2
project_name: example
before:
  hooks:
    - go mod download
archives:
  - id: darwin
    ids: ['darwin']
    formats: [ 'zip' ]
  - id: linux
    ids: [ 'linux']
    formats: [ 'zip' ]
  - id: windows
    ids: ['windows']
    formats: [ 'zip' ]
homebrew_casks:
  - ids:
      - darwin
    url:
      verified: github.com/attachmentgenie/{{.ProjectName}}"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/{{.ProjectName}}"]
          end
    repository:
      owner: attachmentgenie
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
builds:
  - id: darwin
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64
  - id: linux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: windows
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
dockers_v2:
  - images:
      - "ghcr.io/attachmentgenie/{{.ProjectName}}"
    tags:
      - "{{ .Version }}"
      - "v{{ .Major }}"
      - "latest"
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
nfpms:
  - id: linux
    maintainer: 'bram vogelaar <bram@attachmentgenie.com>'
    package_name: "{{.ProjectName}}"
    ids: [ 'linux']
    formats:
      - deb
      - rpm
sboms:
  - artifacts: archive
release:
  prerelease: auto
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
